bugs:
  "GenericBug_Ignore":
    category: None
    description: "Place regexps for generic, high-level bugs to be ignored here"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "importer.py.. line.* in check_timeout"
      -
        "juju_debug_machine*.txt":
            regexp:
            - "ERROR juju.worker runner.go.{1,10} exited .api.. unable to connect to .wss...localhost.{2,10}.environment"
            - "ERROR juju.worker runner.go.{1,10} fatal .cleaner.. watcher iteration.{1,30}error. EOF"
            - "ERROR juju.worker.firewaller firewaller.go.{1,10} failed to lookup.{1,10}machine.{1,10}lxc.{1,10} skipping port change"
      -
        "juju_debug_log.txt":
            regexp:
            - "ERROR juju.worker.firewaller firewaller.go.{1,10} failed to lookup.{1,10}machine.{1,10}lxc.{1,10} skipping port change"
            - "ERROR juju.state.unit unit.go.{3,5} unit ceilometer.. cannot get.{0,5}assigned machine. unit .ceilometer... is not assigned to a machine"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "oil_ci.ssh. Could not setup ssh connection to"
      -
        "console.txt":
            regexp:
            - "No such file or directory.{1,5}artifacts.juju_status.yaml"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "No such file or directory.{1,5}artifacts.juju_status.yaml"
      -
        "tempest_xunit.xml":
            regexp:
            - "cleanUp operation failed"

  "1346340":
    category: None
    description: "deployer fails with no route to host"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "ERROR.*Deployment failed..*No route to host"

  "1352503":
    category: None
    description: "nova-cloud-controller fails to install with neutron-nsx"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit..nova-cloud-controller... machine... agent-state..error details..hook failed...install"

  "1352506":
    category: None
    description: "nova-compute: Failed to reconnect to the hypervisor"
    pipeline_deploy:
      -
        "nova-compute_*_var_log_juju_unit-nova-compute-*.log":
            regexp:
            - "Failed to reconnect to the hypervisor"

  "1358326":
    category: None
    description: "prodstack: nova-vmware hooks failed: cloud-compute-relation-changed"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "nova-vmware.. (.*) in error state..hook failed...cloud-compute-relation-changed..for nova-cloud-controller.cloud-compute"

  "1355265":
    category: None
    description: "hook failed: \"mon-relation-joined\""
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. ceph... machine... agent-state. error details. hook failed...mon-relation-joined"

  "1346597":
    category: None
    description: "mongo timeout? cannot get replica set configuration"
    pipeline_deploy:
      -
        "juju_debug_log.txt":
            regexp:
            - "DEBUG juju.mongo open.go... connection failed, will retry. dial tcp .{16} connection refused"

  "1353529":
    category: None
    description: "nova-vmware: nova-compute-vmware package not found"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. nova-vmware... machine... agent-state. error details. hook failed...install"

  "1372417":
    category: None
    description: "prodstack: Could not query juju status"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "ERROR.*Could not query juju status"

  "1372942":
    category: None
    description: error executing lxc - container failed to start
    pipeline_deploy:
      -
        "juju_status.yaml":
            regexp:
            - "error executing .lxc-start.. The container failed to start.+To get more details, run the container in foreground mode.+Additional information can be obtained by setting the --logfile and --log-priority options"

  "1372941":
    category: None
    description: Prodstack. VolumeBuildErrorException. Volume <id> failed to build and is in ERROR status (tempest fail)
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "failed to build and is in ERROR status"
            - "create_test_server raise ex BuildErrorException"
      -
        "console.txt":
            regexp:
            - "BuildErrorException. Server .{13,36} failed to build and is in ERROR status"
            - "failed to build and is in ERROR status"

  "1372946":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "assertFalse.{1,2000}raise self.failureException.{1,2000}AssertionError: True is not false"

  "1372947":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "SSHTimeout: Connection to the .{1,2000} via SSH timed out.{1,2000}User: .{1,2000}, Password: .{1,2000}"

  "1372949":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "UnboundLocalError: local variable 'agent' referenced before assignment"

  "1372954":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "TimeoutException: Request timed out.{1,2000}Details: Server .{1,2000} failed to reach ACTIVE status.{1,2000}within the required time .{1,2000} Current status: SHUTOFF"

  "1372958":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "Request timed out.{1,2000}Details: Server .{1,2000} failed to reach ACTIVE status within the required time .{1,2000} Current status: BUILD"

  "1372960":
    category: None
    description: "Request timed out while spawning - Server failed to reach ACTIVE status and task state during BUILD (tempest fail)"
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "failed to reach ACTIVE status and task state.{1,2000}within the required time.{1,2000}Current status: BUILD. Current task state: spawning"
      -
        "console.txt":
            regexp:
            - "failed to reach ACTIVE status and task state.{1,2000}within the required time.{1,2000}Current status: BUILD. Current task state: spawning"

  "1372964":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "Unable to find network with name 'private'.{1,2000}returned non-zero exit status 1"

  "1318783":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "No more IP addresses available on network"

  "1372997":
    category: None
    description: oil_ci.deploy.oil_deployer - Deployment timed-out and failed (pipeline_deploy fail)
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "oil_ci.deploy.oil_deployer. Deployment failed.{1,2000}Deployment failed"

  "1372970":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "Object not found.{1,2000}Details: No ResellerAdmin role found"

  "1373020":
    category: None
    description: oil_deployer Deployment failed - Name or service not known (pipeline_deploy fail)
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "oil_ci.deploy.oil_deployer: Deployment failed: .Errno -2. Name or service not known"

  "1373023":
    category: None
    description: Enabled field must be a boolean (tempest fail)
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "'message': 'Enabled field must be a boolean"

  "1373024":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "type object 'ServerRescueV3Test.{1,2000}' has no attribute 'volumes_client'"

  "1373027":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "ServerFault: Got server fault.{1,2000}Details: Failed to attach interface"

  "1373028":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "MismatchError: (.+204.+ != .+200.+|!=:)"

  "1373030":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "itemNotFound.{1,2000}Image not found"

  "1372459":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "itemNotFound.{1,2000}FloatingIpPoolNotFound: Floating ip pool not found"

  "1372461":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "AssertionError. Timed out waiting for.{1,2000}to become reachable"

  "1373035":
    category: None
    description: Volume failed to reach available status within the required time (tempest fail)
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "Volume volume.{1,2000}failed to reach available status within the required time"

  "1371792":
    category: None
    description: "juju bootstrap failures - dpkg lock race condition"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Reading package lists...E: Could not get lock /var/lib/dpkg/lock - open .11. Resource temporarily unavailable.*Unable to lock the administration directory ./var/lib/dpkg/., is another process using it?.*ERROR bootstrap failed"

  "1373402":
    category: None
    description: "No handlers could be found for logger glanceclient.common.http (tempest fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "No handlers could be found for logger .glanceclient.common.http"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "No handlers could be found for logger .glanceclient.common.http"

  "1375220":
    category: None
    description: "swift-storage-relation-changed (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "hook failed.{1,2000}swift-storage-relation-changed"

  "1375876":
    category: None
    description: "prodstack: template container juju-trusty-lxc-template did not stop"
    pipeline_deploy:
      -
        "juju_status.yaml":
            regexp:
            - "agent-state-info. template container .juju-trusty-lxc-template. did not stop"


  "1328950":
    category: None
    description: "[Prodstack] Prepare often fails on upload glance image"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "Failed to prepare deployed cloud.{1,2000}CommunicationError. Error communicating with .{1,2000} timed out"

  "1387670":
    category: None
    description: "Prodstack: Failed to prepare deployed cloud"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "Failed to prepare deployed cloud.{1,2000}ConnectionFailed. Connection to neutron failed"

  "1387688":
    category: None
    description: "
Prodstack: Failed to prepare deployed cloud (NeutronClientException)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "oil_ci.prepare.oil_prepper. Failed to prepare deployed cloud.{1,2000}NeutronClientException. Request Failed. internal server error while processing your request"

  "1386663":
    category: None
    description: "Prodstack: image-service-relation-changed"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "error details. hook failed...image-service-relation-changed"
      -
        "juju_status.yaml":
            regexp:
            - "hook failed...image-service-relation-changed. for glance.image-service"

  "1386672":
    category: None
    description: "Prodstack: identity service relation joined"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "hook failed...identity-service-relation-joined"
      -
        "juju_status.yaml":
            regexp:
            - "hook failed...identity-service-relation-joined. for keystone.identity-service"

  "1389318":
    category: None
    description: "Prodstack: stable juno did not match any file(s) known to git (tempest fail)"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "error. pathspec .stable.juno. did not match any file.s. known to git.+subprocess.CalledProcessError. Command '.'git', 'checkout', 'stable/juno'.' returned non-zero exit status 1"

  "1386963":
    category: None
    description: "Prodstack: cassandra, error details hook failed config-changed (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. cassandra... machine.{1,10} agent-state. error details. hook failed...config-changed"

  "1389332":
    category: None
    description: "Prodstack: Invalid config charm cinder (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "deployer.deploy. Invalid config charm cinder remove-missing=True"

  "1386754":
    category: None
    description: "ceilometer-agent <-> nova-compute relation does not exist for nova-compute-vmware"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Invalid relation in config, service nova-compute not found, rel ceilometer-agent <-> nova-compute"

  "1391266":
    category: None
    description: "Prodstack: Cinder VNX cannot add james-page/partner-testing PPA (deploy fail)"
    pipeline_deploy:
      -
        "*cinder-vnx_*.oil_var_log_juju_unit-cinder-vnx-*log":
            regexp:
            - "Cannot add PPA"

  "1396657":
    category: None
    description: "prodstack unit ceph/2 machine: 3 agent-state error details hook failed install"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. ceph/.. machine. . agent-state. error details. hook failed...install"

  "1393835":
    category: None
    description: "[Prodstack] Invalid config charm cinder-vnx vnx_source_key (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "deployer.deploy. Invalid config charm cinder-vnx vnx_source_key="

  "1397308":
    category: None
    description: "[Prodstack] Permission denied in ceph.client.glance.keyring. (prepare fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "OSError.{9,13} Permission denied. ./tmp/.{25,40}/etc/ceph/ceph.client.glance.keyring"

  "1398282":
    category: None
    description: "[Prodstack] rabbitmq-server/0 hook failed - install Cannot initiate the connection to archive.ubuntu.com"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. rabbitmq-server... machine.{1,12} agent-state. error details. hook failed. .install"

  "1399818":
    category: None
    description: "[Prostack] nova-compute hook failed image-service-relation-changed - can't ssh into hayward-03"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. nova-compute... machine.{1,4} agent-state. error details. hook failed...image-service-relation-changed.+oil_ci.ssh. Could not setup ssh connection to"

  "1403548":
    category: None
    description: "[Prodstack] Failed deployment due to keystone, lxc, hook failed (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. keystone... machine. .{1,3}lxc.{1,3} agent-state. error details. hook failed...config-changed"


  "1387693":
    category: None
    description: "nova-compute-libvirt fails install on precise"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit..nova-compute... machine... agent-state..error details..hook failed...install"

  "1386857":
    category: None
    description: "prepare failing to create networks with valid subnet (prepare fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "NeutronError.{1,2000}message.{1,2000}Invalid input for operation..Gateway is not valid on subnet.{1,2000}type.{1,2000}InvalidInput"
      -
        "console.txt":
            regexp:
            - "NeutronClientException.{9}NeutronError.{6}message.{5}Invalid input for operation..Gateway is not valid on subnet.{6}type.{5}InvalidInput"

  "1397451":
    category: None
    description: "prodstack: unit: mysql/0: machine: 3/lxc/0 agent-state: error details: hook failed: install"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. mysql... machine. .{1,3}lxc.{1,3} agent-state. error details. hook failed...install"
      -
        "mysql_*_var_log_juju_*mysql*.log":
            regexp:
                - "ImportError. No module named six"

  "1405802":
    category: None
    description: "[Prodstack] oil_ci.deploy.oil_deployer: Deployment failed: Env Error - Details: Error : ambiguous relation: neutron-api keystone (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Error.....ambiguous relation...neutron-api keystone. could refer to .neutron-api.identity-admin keystone.identity-admin....neutron-api.identity-service keystone.identity-service"

  "1408037":
    category: None
    description: "serverstack unit swift-storage/2 .. hook failed: install - Invalid Cloud Archive release specified trusty-juno"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Invalid Cloud Archive release specified. trusty-juno"

  "1410876":
    category: None
    description: 'juju: error executing "lxc-clone/wait": lxc_container: utils.c: mkdir_p'
    pipeline_deploy:
      -
        "juju_status.yaml":
            regexp:
                - 'error\s+executing\s+"lxc-(wait|clone)":\s+lxc_container:\s+utils.c:\s+mkdir_p'

  "1400396":
    category: None
    description: "Prodstack cannot add unit 1/1 to service - dial tcp 10.245.0.10 connection refused"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "cannot add unit ... to service .nova-compute.. cannot add unit to service .nova-compute.. Get http.{10,20}MAAS.api.{3,7}nodes"

  "1474183":
    category: None
    description: "Unit ceph/x: agent-state error details hook failed mon-relation-changed"
    pipeline_deploy:
      -
        "*ceph_*_var_log_juju_unit-ceph-*.log":
            regexp:
            - 'OSError: .Errno 22. Invalid argument: ./var/lib/ceph/osd/ceph-\d+.'

  "1398879":
    category: None
    description: "prodstack No available node matches constraints tags=hw-ok - non-oil allocated node"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "409 CONFLICT .No available node matches constraints"
      -
        "juju_status.yaml":
            regexp:
            - "409 CONFLICT .No available node matches constraints"
      -
        "juju_debug_machine-*.txt":
            regexp:
            - "ERROR juju.provisioner provisioner_task.go.{1,5} cannot start.{1,10}instance for machine.{1,10}cannot run instances. cannot run instances.{1,10}gomaasapi: got error back from server. 409 CONFLICT .No available node matches.{1,10}constraints. tags=hw-ok"


  "1405804":
    category: None
    description: "Prodstack oil_ci.deploy.oil_deployer Deployment failed Env Error - Details - Error  cannot add relation neutron-gateway amqp rabbitmq-server amqp relation already exists"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "cannot add relation .neutron-gateway.amqp rabbitmq-server.amqp.. relation already exists"

  "1336339":
    category: None
    description: "prodstack cinder-iscsi charm failure Command vgextend, cinder-volumes, /dev/loop0 returned non-zero exit status 5"
    pipeline_deploy:
      -
        "*cinder_*.oil_var_log_juju_unit-cinder-*.log":
            regexp:
            - "CalledProcessError. Command ...vgextend.....cinder-volumes.....dev.loop.....returned non-zero exit status 5"

  "1318786":
    category: None
    description: "keystone auth EndpointNotFound Endpoint not found"
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "Endpoint not found"


  "1414644":
    category: None
    description: "[Prodstack] NeutronClientException: internal server error while processing your request (tempest fail)"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "NeutronError....Request Failed. internal server error while processing your request"

  "1414656":
    category: None
    description: "[Serverstack] swift-storage fails to install (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit..swift-storage... machine... agent-state..error details..hook failed...install"


  "1414659":
    category: None
    description: "[Serverstack] The server has either erred or is incapable of performing the requested operation (tempest fail)"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "The server has either erred or is incapable of performing the requested operation"


  "1416428":
    category: None
    description: "[Prodstack] contrail-configuration machine 5 agent-state error details hook failed identity-admin-relation-changed (deploy fail)"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "contrail-configuration.*agent-state: error details: hook failed: .identity-admin-relation-change"


  "1417045":
    category: None
    description: "[Prodstack] OILSSHException Could not untar local copy of remote directory (prepare fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "OILSSHException. Could not untar local copy of remote directory"


  "1417049":
    category: None
    description: "Request Failed. internal server error while processing your request"
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "Request Failed. internal server error while processing your request"


  "1417053":
    category: None
    description: "server could not verify that you are authorized to access the document"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "This server could not verify that you are authorized to access the document you requested. Either you supplied the wrong credentials .e.g., bad password., or your browser does not understand how to supply the credentials required"

  "1416437":
    category: None
    description: "Prodstack oil_ci.deploy.oil_deployer Deployment failed ceilometer-agent - KeyError ceilometer-agent"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Deployment failed. 'ceilometer-agent'.{1,2000}KeyError. 'ceilometer-agent'"

  "1422732":
    category: None
    description: "[Prodstack] Internal server error while processing your request (tempest fail)"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "Failed..internal server error while processing your request.....type....HTTPInternalServerError"

  "1425358":
    category: None
    description: "[Prodstack] Deployment failed 'NoneType' object is not iterable (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "oil_ci.deploy.oil_deployer. Deployment failed. .NoneType. object is not iterable"

  "1419041":
    category: None
    description: "boostrap failing with gomaasapi 400"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "ERROR failed to bootstrap environment: cannot start bootstrap instance: gomaasapi: got error back from server: 400 BAD REQUEST.*is not a valid distro_series.*It should be one of"

  "1418235":
    category: None
    description: "contrail-configuration0 machine 5 agent-state error details hook failed identity-admin-relation-changed"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Found unit contrail-configuration.{3,40} in error state. hook failed...identity-admin-relation-changed. for keystone.identity.admin"

  "1433978":
    category: None
    description: "[Prodstack] Failed deployment due to mysql, lxc, hook failed (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. mysql... machine. .{1,3}lxc.{1,3} agent-state. error details. hook failed...config-changed"

  "1433982":
    category: None
    description: "[Prodstack] Glance failed to install (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. glance... machine. .{1,3}lxc.{1,3} agent-state. error details. hook failed...install"

  "1434008":
    category: None
    description: "[Prodstack] OperationalError - Unknown error occurred (tempest fail)"
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "OperationalError..Code..Message.Unknown error occurred...Message...Error...Errors."

  "1430834":
    category: None
    description: "Prodstack: no workspace from node hudson.slaves.* Build Aborted"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Exception when executing the batch command : no workspace from node hudson.slaves.* which is computer hudson.slaves.* and has channel null"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "Exception when executing the batch command : no workspace from node hudson.slaves.* which is computer hudson.slaves.* and has channel null"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "Exception when executing the batch command : no workspace from node hudson.slaves.* which is computer hudson.slaves.* and has channel null"

  "1436436":
    category: None
    description: "[metaswitch] nova-compute unable to locate package calico-compute"
    pipeline_prepare:
      -
        "juju_debug_log.txt":
            regexp:
            - "Unable to locate package calico-compute"

  "1442271":
    category: None
    description: "AssertionError. State change timeout exceeded for boto.test_ec2_volumes (tempest fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "AssertionError. State change timeout exceeded"

  "1453872":
    category: None
    description: "Prodstack: bootstrap instance started but did not change to Deployed state"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "ERROR.*bootstrap instance started but did not change to Deployed state"

  "1430823":
    category: None
    description: "Prodstack: ConnectionFailed. Connection to neutron failed"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "raise exceptions.ConnectionFailed.reason=e..*ConnectionFailed. Connection to neutron failed"

  "1441652":
    category: None
    description: "1.8b1: 502 Proxy Error when trying to access MAAS in browser"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "gomaasapi. got error back from server. 502 Proxy Error"
      -
        "juju_status.yaml":
            regexp:
            - "gomaasapi. got error back from server. 502 Proxy Error"

  "1446248":
    category: None
    description: "Packages cannot be authenticated leading to hook install failures"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "agent-state. error details. hook failed...install"
      -
        "*_var_log_juju_*.log":
            regexp:
                - "WARNING. The following packages cannot be authenticated....*install logger.go..*   .+..+.*install logger.go..* E. There are problems and -y was used without --force-yes.*..*Traceback .most recent call last.."

  "1444365":
    category: None
    description: "Failed to prepare network for deployed cloud - exceptions.Unauthorized"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "_cs_request.*raise exceptions.Unauthorized.message=body.*Unauthorized: Authentication required"

  "1444380":
    category: None
    description: "Failure to prepare network for deployed cloud - NeutronClientException: 500 - HTTPInternalServerError"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "self.prepare_network.*NeutronClientException: 500-.+NeutronError.+message.+ u.Request Failed. internal server error while processing your request.*type.*HTTPInternalServerError"

  "1444394":
    category: None
    description: "pipeline_prepare failure - CommunicationError: Error communicating with glance node"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "Failed to prepare deployed cloud.*glanceclient.common.http.py.*_http_request.*raise exc.CommunicationError.message=message.*Error communicating with http"

  "1447210":
    category: None
    description: "[Prodstack] Inspection failed. Authorization Failed. An unexpected error prevented the server from fulfilling your request (prepare fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "oil_ci.cli.{1,5} Inspection failed. Authorization Failed. An unexpected error prevented the server from fulfilling your request"

  "1453954":
    category: None
    description: "prodstack: 500 error in agent-state-info"
    pipeline_deploy:
      -
         "juju_status.yaml":
           regexp:
           - 'agent-state-info. .gomaasapi. got error back from server. 500 INTERNAL SERVER'
      -
         "console.txt":
           regexp:
           - 'ERROR failed to bootstrap environment. cannot start bootstrap instance. gomaasapi. got error back from server. 500 INTERNAL SERVER ERROR'

  "1454464":
    category: None
    description: "Prodstack: bootstrap fails with no route to host that's succesfully deployed"
    pipeline_deploy:
      -
         "console.txt":
           regexp:
           - "ERROR failed to bootstrap environment. waited for 30m0s without being able to connect. ssh. connect to host.*port 22. No route to host"

  "1441319":
    category: None
    description: "intermittent: failed to retrieve the template to clone: template container juju-trusty-lxc-template did not stop"
    pipeline_deploy:
      -
         "juju_status.yaml":
           regexp:
           - "failed to retrieve the template to clone. template container.*juju-trusty-lxc-template. did not stop"

  "1454468":
    category: None
    description: "win2012hvr2 node deployed by maas but juju status remains pending with juju 1.23.2"
    pipeline_deploy:
      -
         "juju_debug_log.txt":
           regexp:
           - "unit nova-hyperv/0 cannot get assigned machine. unit .nova-hyperv/0. is not assigned to a machine"

  "1456832":
    category: None
    description: "nova-compute/0 fails to install - agent-state: installing"
    pipeline_deploy:
      -
         "juju_status.yaml":
           regexp:
           - "nova-compute/.{11}agent-state. installing"

  "1424678":
    category: None
    description: "Prodstack: glance/0 error details: hook failed: config-changed"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. glance/.. machine. .{1,7} agent-state. error details. hook failed. .config-changed"
      -
        "juju_debug_log.txt":
            regexp:
            - "unit.glance/..config-changed logger.go... AttributeError. .NoneType. object has no attribute .TemplateNotFound.*config-changed"

  "1456997":
    category: None
    description:
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "No valid host was found. Exceeded max scheduling attempts"

  "1339910":
    category: None
    description:
    test_tempest_smoke:
      -
        "nova-cloud-controller_*_var_log_nova_nova-api-os-compute.log":
            regexp:
            - "ERROR nova.api.openstack.*Caught error...OperationalError.{7,10}Too many connections"

  "1457813":
    category: None
    description: "[prodstack] service neutron-calico has no calico-acl-api relation (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "service .neutron.calico. has no .calico.acl.api. relation"

  "1412364":
    category: None
    description: "Icehouse tempest job fails due to mismatch between networkx and decorator versions in LVMISCSIDriver driver"
    test_tempest_smoke:
      -
        "cinder_*_var_log_cinder_cinder-volume.log":
            regexp:
            - "ERROR cinder.volume.manager .req..{8}..{4}..{4}..{4}..{12} . . . . .. Error encountered during initialization of driver. LVMISCSIDriver"

  "1459193":
    category: None
    description: "OperationalError. no such table. ml2_vlan_allocations"
    test_tempest_smoke:
      -
        "nova-cloud-controller_*_var_log_neutron_server.log":
            regexp:
            - "CRITICAL neutron ... OperationalError. .OperationalError. no such table. ml2_vlan_allocations"

  "1459202":
    category: None
    description: " Failed to attach network adapter device (tempest fail)"
    test_tempest_smoke:
      -
        "nova-cloud-controller_*_var_log_nova_nova-api-os-compute.log":
            regexp:
            - "InterfaceAttachFailed: Failed to attach network adapter device"

  "1448150":
    category: None
    description: "Calico bundle generated with neutron-gateway relation with nova-compute without neutron-gateway service"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Invalid relation in config. service neutron-gateway not found. rel neutron-gateway*nova-compute"

  "1457720":
    category: None
    description: "bad credential error"
    pipeline_deploy:
      -
         "juju_debug_log.txt":
           regexp:
           - "Error. invalid entity name or password. ErrorCode. unauthorized access"

  "1454676":
    category: None
    description: "failed to retrieve the template to clone: lxc container creation failed"
    pipeline_deploy:
      -
         "juju_status.yaml":
           regexp:
               - 'wget:\s+unable\s+to\s+resolve\s+host\s+address'

  "1485784":
    category: None
    description: "Error creating container juju-trusty-lxc-template; Failed to parse config"
    pipeline_deploy:
      -
         "juju_status.yaml":
           regexp:
               - 'Failed to parse config:\s+lxc.include\s+=\s+.usr.share.lxc.config.ubuntu-cloud.common.conf'

  "1456933":
    category: None
    description: "sm15k node failed to PXE boot."
    pipeline_deploy:
      -
         "juju_status.yaml":
           regexp:
               - 'agent-state: pending\s+(containers:\s+(\d+/lxc/\d+:\s+instance-id: pending\s+series: (trusty|precise))*)*\s+dns-name: hayward'

  "1461448":
    category: None
    description: "Failed to prepare deployed cloud - raise BadStatusLine(line)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "raise BadStatusLine.line..*BadStatusLine"

  "1449402":
    category: None
    description: "504 Gateway Error in Juju Status"
    pipeline_deploy:
      -
        "juju_status.yaml":
          regexp:
          - "agent-state-info. .gomaasapi. got error back from server. 504 GATEWAY TIMEOUT."
      -
        "console.txt":
            regexp:
            - "cannot start bootstrap instance. gomaasapi. got error back from server. 504 GATEWAY TIMEOUT"

  "1468294":
    category: None
    description: "[Prodstack] JujuTestClientException - Calling juju bootstrap failed (deploy fail)"
    pipeline_deploy:
      -
        "console.txt":
          regexp:
          - "juju bootstrap. failed.{600,800}raise JujuTestClientException"

  "1468579":
    category: None
    description: "juju bootstrap failed - cannot dial mongo to initiate replicaset: no reachable servers"
    pipeline_deploy:
      -
        "console.txt":
          regexp:
          - "replica set. cannot dial mongo to initiate replicaset. no reachable servers.{1,500}ERROR failed to bootstrap environment"

  "1468581":
    category: None
    description: "juju bootstrap fails - Waiting for API to become available ERROR cannot get all blocks: EOF"
    pipeline_deploy:
      -
        "console.txt":
          regexp:
          - "Waiting for API to become available.*ERROR cannot get all blocks. EOF.*Calling .juju bootstrap. failed!"
          - "ERROR connection is shut down.{1,100}Calling .juju bootstrap. failed!"

  "1412621":
    category: None
    description: "juju bootstrap failed - cannot initiate replica set: cannot get replica set status: can't get local.system.replset config from self or any seed (EMPTYCONFIG)"
    pipeline_deploy:
      -
        "console.txt":
          regexp:
          - "can.t get local.system.replset config from self or any seed .EMPTYCONFIG..*ERROR failed to bootstrap environment"

  "1421260":
    category: None
    description: "juju 1.21.1 bootstrap timeout"
    pipeline_deploy:
      -
        "console.txt":
          regexp:
          - "Juju bootstrap timeout"

  "1469159":
    category: None
    description: "error checking if loop0 is in use. open /dev/loop0 operation not permitted (tempest fail)"
    test_tempest_smoke:
      -
        "openstack-dashboard_*_var_log_juju_machine-*-lxc*.log":
          regexp:
          - "ERROR juju.worker.diskmanager lsblk.go.{3,5} error checking if .loop.. is in use. open .dev.loop.. operation not permitted"

  "1469161":
    category: None
    description: "MySQL server has gone away (tempest fail)"
    test_tempest_smoke:
      -
        "mysql_*_var_log_syslog":
          regexp:
          - "ERROR 2006 .HY000. at line .{3,5} MySQL server has gone away"

  "1469169":
    category: None
    description: "Unknown column services.disabled_reason in field list (tempest fail)"
    test_tempest_smoke:
      -
        "cinder_*-cinder-vmware_*_var_log_cinder_cinder-volume.log":
          regexp:
          - "Unknown column .services.disabled_reason. in .field list."

  "1469171":
    category: None
    description: "Table cinder.services doesn't exist (tempest fail)"
    test_tempest_smoke:
      -
        "cinder_*-cinder-vmware_*_var_log_upstart_cinder-volume.log":
          regexp:
          - "ProgrammingError.{8,20}Table .cinder.services. doesn.t exist"
    pipeline_prepare:
      -
        "cinder_*-cinder-vnx_*_var_log_cinder_cinder-scheduler.log":
          regexp:
          - "ProgrammingError.{8,20}Table .cinder.services. doesn.t exist"

  "1469309":
    category: None
    description: "cinder config-change hook failure:  Can't remove VGs when partial LVs exist"
    pipeline_deploy:
      -
        "cinder_*_var_log_juju_unit-cinder-*.log":
            regexp:
            - "To remove them unconditionally use: vgreduce --removemissing --force."

  "1476418":
    category: None
    description: "cinder config-change hook failure: cinder-volumes already exists"
    pipeline_deploy:
      -
        "cinder_*_var_log_juju_unit-cinder-*.log":
            regexp:
            - "A volume group called cinder-volumes already exists"

  "1473446":
    category: None
    description: "cinder config-change hook failure: cinder-volumes not found"
    pipeline_deploy:
      -
        "cinder_*_var_log_juju_unit-cinder-*.log":
            regexp:
                - 'Volume group "cinder-volumes" not found'

  "1470241":
    category: None
    description: "Prodstack: nvp-transport-node/0 - error details: hook failed: config-changed - openvswitch-switch : Depends: openvswitch-common (= 2.3.2.42955) but it is not going to be installed"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "unit. nvp-transport-node/.. machine. agent-state. error details. hook failed. .config-changed"
      -
        "neutron-gateway_*-nvp-transport-node_*_var_log_juju_unit-nvp-transport-node-*.log":
            regexp:
            - "config-changed subprocess.CalledProcessError. Command ...apt-get., .--assume-yes., .--option=Dpkg..Options..=--force-confold', .install., u.openvswitch-datapath-dkms., u.openvswitch-switch., u.nicira-ovs-hypervisor-node.."

  "1429891":
    category: None
    description: "Prodstack: bzr: ERROR: Connection closed: Unexpected end of message"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "Could not branch.{100,200}ConnectionReset reading response for .BzrDir.open_2.1.{100,200}bzr. ERROR. Connection closed. Unexpected end of message. Please check connectivity and permissions, and report a bug if problems persist"

  "1272283":
    category: None
    description: "error Errno 111 Connection refused"
    test_tempest_smoke:
      -
        "console.txt":
          regexp:
          - "error...Errno 111. Connection refused.*tempest.thirdparty.boto.test_ec2_keys.EC2KeysTest"
      -
        "tempest_xunit.xml":
          regexp:
          - "Connection.{1,5}refused"

  "1472602":
    category: None
    description: "Start tag expected"
    test_tempest_smoke:
      -
        "console.txt":
          regexp:
          - "XMLSyntaxError. Start tag expected. .<. not found, line 1, column 1"
      -
        "tempest_xunit.xml":
          regexp:
          - "Start tag expected. .{1,2}<.{1,2} not found, line 1, column 1"

  "1474688":
    category: None
    description: "Prodstack: HTTPInternalServerError: 500 Internal Server Error Failed to upload image"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "ERROR. glanceclient.common.http. Request returned failure status.{1,1300}HTTPInternalServerError. 500 Internal Server Error.{1,5}Failed to upload image"
            - "ERROR. glanceclient.common.http. Request returned failure status.{1,1300}HTTPInternalServerError. HTTPInternalServerError .HTTP 500."

  "1461192":
    category: None
    description: "nova-compute: Failed to reconnect to the hypervisor"
    pipeline_deploy:
      -
        "nova-compute_*_var_log_juju_unit-nova-compute-*.log":
            regexp:
            - "arg 2 must contain only strings"

  "1479220":
    category: None
    description: "Prodstack: branch issue for neutron-calico charm"
    pipeline_deploy:
      -
        "console.txt":
            regexp:
            - "deployer.charm. Could not branch.{1,100}to trusty.neutron-calico"

  "1481484":
    category: None
    description: "mysqld exceeds max connections limit"
    pipeline_deploy:
      -
        "neutron-api_*_var_log_upstart_neutron-server.log":
            regexp:
            - "OperationalError.{10}Too many connections"

  "1481773":
    category: None
    description: "Invalid input for field (tempest fail)"
    test_tempest_smoke:
      -
        "tempest_xunit.xml":
            regexp:
            - "Invalid input for field.{1,3}url.{1,5}The value is.{1,3}url-tempest-"

  "1482770":
    category: None
    description: "Prodstack [prepare]: IOError: [Errno 13] Permission denied: '/mnt/images/lxc/precise-server-cloudimg-amd64.img'"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "Failed to prepare deployed cloud.{1,2000}IOError. .Errno 13. Permission denied. '/mnt/images/lxc/precise-server-cloudimg-amd64.img"

  "1482790":
    category: None
    description: "Prodstack[Tempest]: subprocess.CalledProcessError - juju status returned non-zero exit status 124 while saving test artifacts"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "subprocess.CalledProcessError. Command ...timeout., .5., .juju., .status., .--format=json., .-e., u.ci-oil-slave.{1,2}... returned non-zero exit status 124"

  "1482796":
    category: None
    description: "Prodstack[Tempest]: raise BadStatus Line while deleting glance image"
    test_tempest_smoke:
      -
        "console.txt":
            regexp:
            - "raise BadStatusLine.line.{1,20}BadStatusLine"

  "1484119":
    category: None
    description: "TypeError in oil-ci's api module - complains that 'Tenant' object has no attribute '__getitem__'"
    test_bundletests:
      -
        "console.txt":
            regexp:
            - "do_verification_test.{0,6}raise e.{0,6}TypeError. .Tenant. object.{0,15} has no attribute .__getitem__"
            - "oil_ci.cli.api.py.. line 518. in do_verification_test"
    test_cloud_image:
      -
        "console.txt":
            regexp:
            - "do_verification_test.{0,6}raise e.{0,6}TypeError. .Tenant. object.{0,15} has no attribute .__getitem__"
            - "oil_ci.cli.api.py.. line 518. in do_verification_test"

  "1484983":
    category: None
    description: "Prodstack[test_cloud_image]: runs out of floating IPs"
    test_cloud_image:
      -
        "console.txt":
            regexp:
            - "No more floating ips in pool ext-net"

  "1486604":
    category: None
    description: "oil_ci/juju/client.py got a non-zero exit status CalledProcessError when using subprocess (test_bundletests failure)"
    test_bundletests:
      -
        "console.txt":
            regexp:
            - "subprocess.CalledProcessError.{1,150}returned non-zero exit status"

  "1489394":
    category: None
    description: "[Prodstack] OILPreparationFailure - network.py expects result to be a dict, but it is a None (prepare fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "network.{0,8}LOG.info.result..stdout.{0,10}TypeError. .NoneType. object has no attribute .__getitem__"

  "1489943":
    category: None
    description: "Prodstack[test_cloud_image]: failed to boot image"
    test_cloud_image:
      -
        "console.txt":
            regexp:
            - "instance status. ERROR"

  "1490009":
    category: None
    description: "Prodstack[test_cloud_image]: failed before calling nosetest"
    test_cloud_image:
      -
        "console.txt":
            regexp:
            - "Test run cloud_image failed"

  "1491397":
    category: None
    description: "[Prodstack] Bad router request. Router already has a port on subnet (prepare fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "Bad router request. Router already has a port on subnet"

  "1491496":
    category: None
    description: "[Prodstack] Unable to complete operation for network. The IP address is in use. (prepare fail)"
    pipeline_prepare:
      -
        "console.txt":
            regexp:
            - "IpAddressInUseClient. Unable to complete operation for network .{36}. The IP address .{4,20} is in use"
